service: nestedvarstest
plugins:
  - print

custom:
  stage: dev
  nested: ${{file(./config.${{self:custom.stage}}.json)}}

provider:
  name: aws
  runtime: nodejs6.10
  variableSyntax: "\\${{([\\s\\S]+?)}}"

functions:
  hello:
    handler: handler.hello
